CREATE TABLE `daily` (
  `id` bigint NOT NULL AUTO_INCREMENT,
  `created_at` datetime(6) NOT NULL,
  `updated_at` datetime(6) NOT NULL,
  `neighborhood` varchar(30) NOT NULL,
  `zip_code` varchar(8) NOT NULL,
  `city` varchar(30) NOT NULL,
  `ibge_code` varchar(255) NOT NULL,
  `complement` varchar(100) DEFAULT NULL,
  `date_service` datetime(6) NOT NULL,
  `state` varchar(2) NOT NULL,
  `address` varchar(60) NOT NULL,
  `reason_cancellation` varchar(255) DEFAULT NULL,
  `number` varchar(10) NOT NULL,
  `observations` varchar(255) DEFAULT NULL,
  `quantity_bathrooms` int NOT NULL,
  `quantity_kitchens` int NOT NULL,
  `quantity_others` int NOT NULL,
  `quantity_yards` int NOT NULL,
  `quantity_bedrooms` int NOT NULL,
  `quantity_rooms` int NOT NULL,
  `status` varchar(255) NOT NULL DEFAULT 'NO_PAYMENT',
  `time_service` int NOT NULL,
  `value_commission` decimal(19,2) NOT NULL,
  `price` decimal(19,2) NOT NULL,
  `customer_id` bigint NOT NULL,
  `housekeeper_id` bigint DEFAULT NULL,
  `job_id` bigint NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`job_id`) REFERENCES `jobs` (`id`),
  FOREIGN KEY (`housekeeper_id`) REFERENCES `users` (`id`),
  FOREIGN KEY (`customer_id`) REFERENCES `users` (`id`)
);
